package constants

// AllowedMimeTypes Список поддерживаемых mimetype
var AllowedMimeTypes = map[string]struct{}{
	"application/ogg":               {},
	"application/pdf":               {},
	"application/zip":               {},
	"application/gzip":              {},
	"application/msword":            {},
	"audio/mp4":                     {},
	"audio/aac":                     {},
	"audio/mpeg":                    {},
	"audio/ogg":                     {},
	"audio/webm":                    {},
	"image/gif":                     {},
	"image/jpeg":                    {},
	"image/pjpeg":                   {},
	"image/png":                     {},
	"image/svg+xml":                 {},
	"image/tiff":                    {},
	"image/webp":                    {},
	"video/mpeg":                    {},
	"video/mp4":                     {},
	"video/ogg":                     {},
	"video/quicktime":               {},
	"video/webm":                    {},
	"video/x-ms-wmv":                {},
	"video/x-flv":                   {},
	"application/vnd.ms-excel":      {},
	"application/vnd.ms-powerpoint": {},
}
