basePath: /api/v1
definitions:
  health.HealthResponse:
    properties:
      status:
        example: ok
        type: string
      time:
        example: "2023-01-01T12:00:00Z"
        type: string
    type: object
  health.StatusResponse:
    properties:
      status:
        example: running
        type: string
      timestamp:
        example: "2023-01-01T12:00:00Z"
        type: string
      version:
        example: 1.0.0
        type: string
    type: object
  messages.BulkCampaignResponse:
    properties:
      created_at:
        example: "2023-01-01T12:00:00Z"
        type: string
      id:
        example: uuid
        type: string
      initiator:
        example: user@example.com
        type: string
      media_filename:
        example: image.jpg
        type: string
      media_mime:
        example: image/jpeg
        type: string
      media_type:
        example: image
        type: string
      message:
        example: Текст сообщения
        type: string
      messages_per_hour:
        example: 20
        type: integer
      name:
        example: Летняя акция
        type: string
      processed_count:
        example: 45
        type: integer
      status:
        example: started
        type: string
      total:
        example: 100
        type: integer
    type: object
  messages.BulkSendStartResponse:
    properties:
      message:
        example: Bulk send started in background
        type: string
      success:
        example: true
        type: boolean
      total:
        example: 123
        type: integer
    type: object
  messages.SendMediaMessageRequest:
    properties:
      async:
        example: true
        type: boolean
      file_data:
        example: base64_encoded_data
        type: string
      filename:
        example: image.png
        type: string
      message:
        example: Сообщение с медиа
        type: string
      message_type:
        example: image
        type: string
      mime_type:
        example: image/png
        type: string
      phone_number:
        example: "79991234567"
        type: string
    required:
    - file_data
    - filename
    - message_type
    - mime_type
    - phone_number
    type: object
  messages.SendMessageRequest:
    properties:
      async:
        example: true
        type: boolean
      message:
        example: Привет! Это тестовое сообщение
        type: string
      phone_number:
        example: "79991234567"
        type: string
    required:
    - message
    - phone_number
    type: object
  messages.SendMessageResponse:
    properties:
      id:
        example: message_id_123
        type: string
      message:
        example: Message sent successfully
        type: string
      status:
        example: sent
        type: string
      success:
        example: true
        type: boolean
    type: object
  settings.WhatsGateSettings:
    properties:
      api_key:
        example: your_api_key
        type: string
      base_url:
        example: https://whatsgate.ru/api/v1
        type: string
      whatsapp_id:
        example: your_whatsapp_id
        type: string
    required:
    - api_key
    - whatsapp_id
    type: object
  types.AppErrorResponse:
    properties:
      code:
        example: INVALID_PHONE
        type: string
      context:
        allOf:
        - $ref: '#/definitions/types.ErrorContext'
        description: Контекстная информация
      description:
        example: Phone number must be exactly 11 digits and start with 7
        type: string
      http_status:
        description: HTTP информация
        example: 400
        type: integer
      message:
        example: Invalid phone number format
        type: string
      severity:
        description: Метаданные
        example: MEDIUM
        type: string
      stack:
        description: Техническая информация
        items:
          $ref: '#/definitions/types.StackFrame'
        type: array
      timestamp:
        example: "2023-01-01T12:00:00Z"
        type: string
      type:
        description: Основная информация
        example: VALIDATION_ERROR
        type: string
      version:
        description: Версионирование
        example: 1.0.0
        type: string
    type: object
  types.ErrorContext:
    properties:
      component:
        example: send_message_handler
        type: string
      ip:
        example: 192.168.1.1
        type: string
      metadata:
        additionalProperties: true
        type: object
      method:
        example: POST
        type: string
      operation:
        example: send_message
        type: string
      path:
        example: /messages/send
        type: string
      request_id:
        example: req-123
        type: string
      resource_id:
        example: campaign-123
        type: string
      session_id:
        example: sess-789
        type: string
      user_agent:
        example: Mozilla/5.0...
        type: string
      user_id:
        example: user-456
        type: string
    type: object
  types.StackFrame:
    properties:
      file:
        example: main.go
        type: string
      function:
        example: main.main
        type: string
      line:
        example: 42
        type: integer
    type: object
  types.SuccessResponse:
    properties:
      message:
        example: Operation completed successfully
        type: string
      success:
        example: true
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Сервис для отправки сообщений через WhatsApp с использованием API WhatGate
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: WhatsApp Service API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Проверяет работоспособность сервиса
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Проверка работоспособности сервиса
      tags:
      - health
  /messages/bulk-send:
    post:
      consumes:
      - multipart/form-data
      description: Отправляет сообщения на несколько номеров. Поддерживает отправку
        медиа и текста. messages_per_hour обязателен и > 0. Все рассылки асинхронные.
        Тип сообщения для media определяется автоматически по mime_type.
      parameters:
      - description: Текст сообщения
        in: formData
        name: message
        required: true
        type: string
      - description: Асинхронно (true/false)
        in: formData
        name: async
        type: boolean
      - description: Сколько сообщений в час (обязателен, > 0)
        in: formData
        name: messages_per_hour
        required: true
        type: integer
      - description: Файл с номерами (xlsx)
        in: formData
        name: numbers_file
        required: true
        type: file
      - description: Медиа-файл (опционально, тип определяется по mime_type)
        in: formData
        name: media_file
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Запуск рассылки
          schema:
            $ref: '#/definitions/messages.BulkSendStartResponse'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Массовая рассылка сообщений
      tags:
      - messages
  /messages/campaigns:
    get:
      consumes:
      - application/json
      description: Возвращает список всех массовых рассылок с их статусами
      produces:
      - application/json
      responses:
        "200":
          description: Список рассылок
          schema:
            items:
              $ref: '#/definitions/messages.BulkCampaignResponse'
            type: array
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Получить список рассылок
      tags:
      - messages
  /messages/campaigns/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает детальную информацию о конкретной рассылке по ID
      parameters:
      - description: ID рассылки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Детали рассылки
          schema:
            $ref: '#/definitions/messages.BulkCampaignResponse'
        "404":
          description: Рассылка не найдена
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Получить детали рассылки
      tags:
      - messages
  /messages/send:
    post:
      consumes:
      - application/json
      description: Отправляет текстовое сообщение через WhatsApp
      parameters:
      - description: Параметры сообщения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/messages.SendMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/messages.SendMessageResponse'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Отправить текстовое сообщение
      tags:
      - messages
  /messages/send-media:
    post:
      consumes:
      - application/json
      description: Отправляет сообщение с медиа-файлом через WhatsApp
      parameters:
      - description: Параметры медиа-сообщения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/messages.SendMediaMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/messages.SendMessageResponse'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Отправить медиа-сообщение
      tags:
      - messages
  /messages/test-send:
    post:
      consumes:
      - multipart/form-data
      description: Отправляет тестовое сообщение на один номер, принимает multipart/form-data
        (phone, message, media_file)
      parameters:
      - description: Номер телефона
        in: formData
        name: phone
        required: true
        type: string
      - description: Текст сообщения
        in: formData
        name: message
        required: true
        type: string
      - description: Медиа-файл (опционально)
        in: formData
        name: media_file
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/messages.SendMessageResponse'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Тестовая отправка сообщения (текст/медиа)
      tags:
      - messages
  /settings:
    get:
      consumes:
      - application/json
      description: Возвращает текущие настройки WhatGate API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/settings.WhatsGateSettings'
      summary: Получить настройки WhatGate
      tags:
      - settings
    put:
      consumes:
      - application/json
      description: Обновляет настройки WhatGate API
      parameters:
      - description: Настройки WhatGate
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/settings.WhatsGateSettings'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/settings.WhatsGateSettings'
        "400":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Обновить настройки WhatGate
      tags:
      - settings
  /settings/reset:
    delete:
      consumes:
      - application/json
      description: Сбрасывает настройки WhatGate API (удаляет сохраненные данные)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SuccessResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/types.AppErrorResponse'
      summary: Сбросить настройки WhatGate
      tags:
      - settings
  /status:
    get:
      consumes:
      - application/json
      description: Возвращает текущий статус и информацию о сервисе
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.StatusResponse'
      summary: Статус сервиса
      tags:
      - status
securityDefinitions:
  BearerAuth:
    description: 'Введите токен в формате: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
